name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: install packages
        run: make install
            
      - name: install packages
        run: make install

      - name: List installed packages
        run: pip list

      - name: lint
        run: make lint
 
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
